name: actions example
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Build Docker image
        run: |
          docker build -t gad:latest .

      - name: Tag & Push to ACR
        run: |
          docker tag gad:latest cidemo.azurecr.io/gad:latest
          docker push cidemo.azurecr.io/gad:latest

      - name: Deploy to Azure Container Apps
        uses: azure/cli@v2
        with:
          inlineScript: |
            az containerapp update --name gad --resource-group Meet --image cidemo.azurecr.io/gad:latest
